{"name": "test_workspace_functionality", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'workflows' in URL, but got https://app.respond.io/space/241150/dashboard\nassert 'workflows' in 'https://app.respond.io/space/241150/dashboard'", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5e348afc931463a95d15921060e2890a\")>\nlogin_data = {'dashboard_url': 'https://app.respond.io/space/241150/dashboard', 'invalid_email': 'bismarespond.io@yopmail.com', 'login_url': 'https://app.respond.io/user/login', 'valid_email': 'bidmarespond.io@yopmail.com', ...}\n\n    def test_workspace_functionality(driver, login_data):\n        # Perform login\n        login_page = LoginPage(driver)\n        login_page.login(login_data['valid_email'], login_data['valid_password'])\n        workspace_page = WorkspacePage(driver)\n        workspace_page.navigate_to_workspace_action()\n        workspace_page.add_workspace_screen()\n        current_url = driver.current_url\n>       assert \"workflows\" in current_url, f\"Expected 'workflows' in URL, but got {current_url}\"\nE       AssertionError: Expected 'workflows' in URL, but got https://app.respond.io/space/241150/dashboard\nE       assert 'workflows' in 'https://app.respond.io/space/241150/dashboard'\n\ntests\\test_workspace.py:14: AssertionError"}, "start": 1722710528009, "stop": 1722710539654, "uuid": "b8be2053-b3cc-4d6a-8023-a181e03abc77", "historyId": "c506d1bcab86e29833f8b448a46f8225", "testCaseId": "c506d1bcab86e29833f8b448a46f8225", "fullName": "tests.test_workspace#test_workspace_functionality", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_workspace"}, {"name": "host", "value": "DESKTOP-1RESUV2"}, {"name": "thread", "value": "14896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_workspace"}]}